namespace PIM.B2b;

public static class MagentoCsvContract
{
  public static readonly IReadOnlyList<string> ProductHeaders =
  [
    "Šifra artikla",
    "EAN",
    "Spletne strani",
    "Naziv artikla EN",
    "Naziv artikla",
    "Proizvajalec",
    "Dobavitelj",
    "ABC klasifikacija",
    "Merska enota",
    "Oznaka tarifa",
    "Država proizvoda",
    "Bruto teža",
    "Enota bruto teže",
    "Neto teža",
    "Enota neto teže",
    "Volumen",
    "Enota volumna",
    "Dolžina paketa",
    "Enota dolžine paketa",
    "Širina paketa",
    "Enota širine paketa",
    "Višina paketa",
    "Enota višine paketa",
    "Kategorije svetila ANG",
    "Kategorije svetila SLO",
    "Kategorije vid ANG",
    "Kategorije vid SLO",
    "Cena B2B",
    "Cena B2C",
    "Popust",
    "Valuta",
    "DDV",
    "PAK2",
    "Omejitev pri naročanju",
    "Skupina popusta",
    "S popust %",
    "Posebni popust za stranko",
    "Glavna slika",
    "Ostale slike",
    "Glavni dokument",
    "Vloge dokumentov",
    "Ostali dokumenti",
    "VID trenutna zaloga",
    "VID naročena količina",
    "VID količina za odpremo",
    "VID razpoložljiva količina",
    "VID naročena količina dobaviteljem",
    "VID datum dobave",
    "VID koli. prihodnjih dobav",
    "Dobavitelj zaloga",
    "Dobavitelj naročena zaloga",
    "Dobavitelj datum",
    "Skladišče",
    "Grlo",
    "Svetilka vključuje svetlobni vir",
    "Senzor gibanja",
    "Max moč sijalke",
    "Garancija",
    "Zračni pretok",
    "Uporaba ANG",
    "Uporaba SLO",
    "Način montaže ANG",
    "Način montaže SLO",
    "Simbol atributa",
    "Baterija",
    "Kapaciteta baterije",
    "Kot svetlobnega snopa",
    "Enota kota svetlobnega snopa",
    "Presek kabla",
    "Višina stropne kapice",
    "Enota višine stropne kapice",
    "Širina stropne kapice",
    "Enota širine stropne kapice",
    "Čas polnjenja",
    "Način polnjenja ANG",
    "Način polnjenja SLO",
    "Nazivna jakost toka",
    "Nazivna napetost",
    "Nazivna moč",
    "Kolekcija",
    "Temperatura barve",
    "Komentarji",
    "Dopolnilna barva I ANG",
    "Dopolnilna barva I SLO",
    "Dopolnilna barva II ANG",
    "Dopolnilna barva II SLO",
    "Dopolnilni simbol tkanine iz vzorčne škatle I",
    "Dopolnilni material I ANG",
    "Dopolnilni material I SLO",
    "Dopolnilni material II ANG",
    "Dopolnilni material II SLO",
    "Dopolnilni material III ANG",
    "Dopolnilni material III SLO",
    "Indeks barvnega videza (CRI)",
    "Vrsta toka",
    "Izvrtina (cutout)",
    "Kot detekcije",
    "Razdalja detekcije",
    "Hitrost detekcije",
    "Premer",
    "Višina",
    "Enota višine",
    "Dolžina",
    "Enota dolžine",
    "Širina",
    "Enota širine",
    "Zatemnljivo ANG",
    "Zatemnljivo SLO",
    "Razdalja od stene",
    "Enota razdalje od stene",
    "EAN koda",
    "Električni razred ANG",
    "Režim nujne osvetlitve ANG",
    "Režim nujne osvetlitve SLO",
    "Energijski razred",
    "Ekvivalent",
    "Simbol tkanine iz vzorčne škatle",
    "Svetlobni tok",
    "Enota svetlobnega toka",
    "Frekvenca",
    "Enota frekvence",
    "Bruto teža (2)",
    "Enota bruto teže (2)",
    "Nastavitev višine",
    "Razpon nastavitve višine",
    "Enota razpona nastavitve višine",
    "Višina daljše roke",
    "Enota višine daljše roke",
    "Višina senčnika reflektorja",
    "Enota višine senčnika reflektorja",
    "Višina krajše roke",
    "Enota višine krajše roke",
    "Dimenzije odprtine",
    "Enota dimenzij odprtine",
    "Oblika odprtine ANG",
    "Oblika odprtine SLO",
    "Ikone",
    "IK stopnja",
    "Montažna višina",
    "IP stopnja zaščite",
    "Oblika svetilke ANG",
    "Oblika svetilke SLO",
    "Prevladujoča barva ANG",
    "Prevladujoča barva SLO",
    "Prevladujoč material ANG",
    "Prevladujoč material SLO",
    "Dolžina podnožja",
    "Enota dolžine podnožja",
    "Dolžina horizontalne roke",
    "Enota dolžine horizontalne roke",
    "Dolžina senčnika",
    "Enota dolžine senčnika",
    "Dolžina vertikalne roke",
    "Enota dolžine vertikalne roke",
    "Življenjska doba",
    "Vrsta svetlobnega vira ANG",
    "Vrsta svetlobnega vira SLO",
    "Luks",
    "Model",
    "Vrtenje motorja",
    "Neto teža (2)",
    "Enota neto teže (2)",
    "Hrup",
    "Število svetlobnih segmentov",
    "Število svetlobnih virov",
    "Število paketov",
    "Število ciklov polnjenja",
    "PCN",
    "Kosov na karton",
    "Višina paketa I",
    "Višina paketa II",
    "Višina paketa III",
    "Enota višine paketa I",
    "Enota višine paketa II",
    "Enota višine paketa III",
    "Dolžina paketa I",
    "Dolžina paketa II",
    "Dolžina paketa III",
    "Enota dolžine paketa I",
    "Enota dolžine paketa II",
    "Enota dolžine paketa III",
    "Volumen paketa",
    "Enota volumna paketa",
    "Širina paketa I",
    "Širina paketa II",
    "Širina paketa III",
    "Enota širine paketa I",
    "Enota širine paketa II",
    "Enota širine paketa III",
    "Faktor moči",
    "Ime izdelka",
    "Razdelitev na segmente",
    "Velikost",
    "Podnožje / socket",
    "Dolžina spuščenega stropa",
    "Enota dolžine spuščenega stropa",
    "Solarni panel",
    "Solarna moč",
    "Slog ANG",
    "Slog SLO",
    "Tehnična opomba",
    "Časovna zakasnitev",
    "Vrsta kabla",
    "Video",
    "Napetost",
    "Enota napetosti",
    "Širina podnožja",
    "Enota širine podnožja",
    "Širina senčnika reflektorja",
    "Enota širine senčnika reflektorja",
    "Delovna temperatura",
    "Delovni čas",
    "Združljivo z",
  ];

  public static readonly IReadOnlyList<string> CustomerHeaders =
  [
    "Šifra stranke", "Naziv", "E-pošta", "Tel. številko", "Uporabniki", "Skupina (Magento)",
    "Cenik", "Plačnik", "Popust polno pakiranje", "Vrednostni rabat", "Rabat prag 1",
    "Rabat % 1", "Rabat prag 2", "Rabat % 2", "Rabat prag 3", "Rabat % 3",
    "B2B+", "Skupine popustov", "Popust NW"
  ];

  public static Dictionary<string, string?> EmptyProductRow()
    => Empty(ProductHeaders);

  public static Dictionary<string, string?> EmptyCustomerRow()
    => Empty(CustomerHeaders);

  private static Dictionary<string, string?> Empty(IEnumerable<string> headers)
  {
    var values = new Dictionary<string, string?>(StringComparer.Ordinal);
    foreach (var header in headers) values[header] = null;
    return values;
  }
}
