namespace PIM.B2b;

public static class MagentoCsvContract
{
  public static readonly IReadOnlyList<string> ProductHeaders =
  [
    "Šifra artikla",
    "EAN",
    "Spletne strani",
    "Naziv artikla EN",
    "Naziv artikla",
    "Proizvajalec",
    "Dobavitelj",
    "ABC klasifikacija",
    "Merska enota",
    "Oznaka tarifa",
    "Država proizvoda",
    "Bruto teža [kg]",
    "Neto teža [kg]",
    "Volumen [m3]",
    "Dolžina paketa [mm]",
    "Širina paketa [mm]",
    "Višina paketa [mm]",
    "Kategorije svetila ANG",
    "Kategorije svetila SLO",
    "Kategorije vid ANG",
    "Kategorije vid SLO",
    "Cena B2B",
    "Cena B2C",
    "Popust na artikel",
    "Valuta",
    "DDV",
    "Pakirna količina",
    "Omejitev pri naročanju",
    "Skupina popusta",
    "S popust %",
    "Posebni popust za stranko",
    "Glavna slika",
    "Ostale slike",
    "Glavni dokument",
    "Vloge dokumentov",
    "Ostali dokumenti",
    "VID trenutna zaloga",
    "VID naročena količina",
    "VID količina za odpremo",
    "VID razpoložljiva količina",
    "VID naročena količina dobaviteljem",
    "VID datum dobave",
    "VID koli. prihodnjih dobav",
    "Dobavitelj zaloga",
    "Dobavitelj naročena zaloga",
    "Dobavitelj datum",
    "Skladišče",
    "Grlo",
    "Svetilka vključuje svetlobni vir",
    "Senzor gibanja",
    "Max moč sijalke",
    "Garancija",
    "Zračni pretok",
    "Uporaba ANG",
    "Uporaba SLO",
    "Način montaže ANG",
    "Način montaže SLO",
    "Simbol atributa",
    "Baterija",
    "Kapaciteta baterije",
    "Kot svetlobnega snopa [°]",
    "Presek kabla",
    "Višina stropne kapice [cm]",
    "Širina stropne kapice [cm]",
    "Čas polnjenja",
    "Način polnjenja ANG",
    "Način polnjenja SLO",
    "Nazivna jakost toka",
    "Nazivna napetost",
    "Nazivna moč [W]",
    "Kolekcija",
    "Temperatura barve [K]",
    "Dopolnilna barva I ANG",
    "Dopolnilna barva I SLO",
    "Dopolnilna barva II ANG",
    "Dopolnilna barva II SLO",
    "Dopolnilni simbol tkanine iz vzorčne škatle I",
    "Dopolnilni material I ANG",
    "Dopolnilni material I SLO",
    "Dopolnilni material II ANG",
    "Dopolnilni material II SLO",
    "Dopolnilni material III ANG",
    "Dopolnilni material III SLO",
    "Indeks barvnega videza (CRI)",
    "Vrsta toka",
    "Izvrtina (cutout)",
    "Kot detekcije",
    "Razdalja detekcije",
    "Hitrost detekcije",
    "Premer [mm]",
    "Višina [mm]",
    "Dolžina [mm]",
    "Širina [mm]",
    "Zatemnljivo ANG",
    "Zatemnljivo SLO",
    "Razdalja od stene [cm]",
    "EAN koda",
    "Električni razred ANG",
    "Režim nujne osvetlitve ANG",
    "Režim nujne osvetlitve SLO",
    "Energijski razred",
    "Ekvivalent",
    "Simbol tkanine iz vzorčne škatle",
    "Svetlobni tok [lm]",
    "Frekvenca [Hz]",
    "Bruto teža (2) [kg]",
    "Nastavitev višine",
    "Razpon nastavitve višine [cm]",
    "Višina daljše roke [cm]",
    "Višina senčnika reflektorja [cm]",
    "Višina krajše roke [cm]",
    "Dimenzije odprtine [cm]",
    "Oblika odprtine ANG",
    "Oblika odprtine SLO",
    "Ikone",
    "IK stopnja",
    "Montažna višina",
    "IP stopnja zaščite",
    "Oblika svetilke ANG",
    "Oblika svetilke SLO",
    "Prevladujoča barva ANG",
    "Prevladujoča barva SLO",
    "Prevladujoč material ANG",
    "Prevladujoč material SLO",
    "Dolžina podnožja [cm]",
    "Dolžina horizontalne roke [cm]",
    "Dolžina senčnika [cm]",
    "Dolžina vertikalne roke [cm]",
    "Življenjska doba [h]",
    "Vrsta svetlobnega vira ANG",
    "Vrsta svetlobnega vira SLO",
    "Luks",
    "Model",
    "Vrtenje motorja",
    "Neto teža (2) [kg]",
    "Hrup",
    "Število svetlobnih segmentov",
    "Število svetlobnih virov",
    "Število paketov",
    "Število ciklov polnjenja",
    "PCN",
    "Kosov na karton",
    "Višina paketa I [cm]",
    "Višina paketa II [cm]",
    "Višina paketa III [cm]",
    "Dolžina paketa I [cm]",
    "Dolžina paketa II [cm]",
    "Dolžina paketa III [cm]",
    "Volumen paketa [dm3]",
    "Širina paketa I [cm]",
    "Širina paketa II [cm]",
    "Širina paketa III [cm]",
    "Faktor moči",
    "Ime izdelka",
    "Razdelitev na segmente",
    "Velikost",
    "Podnožje / socket",
    "Dolžina spuščenega stropa [cm]",
    "Solarni panel",
    "Solarna moč",
    "Slog ANG",
    "Slog SLO",
    "Tehnična opomba",
    "Časovna zakasnitev",
    "Vrsta kabla",
    "Video",
    "Napetost [V]",
    "Širina podnožja [cm]",
    "Širina senčnika reflektorja [cm]",
    "Delovna temperatura",
    "Delovni čas",
    "Združljivo z",
    "Količina odprodaje",
    "Popust odprodaje %",
    "Rabatna skupina artikla",
    "Rabatna skupina ERP",
  ];

  public static readonly IReadOnlyList<string> CustomerHeaders =
  [
    "Šifra stranke", "Naziv", "E-pošta", "Tel. številko", "Uporabniki", "Skupina (Magento)",
    "Cenik", "Plačnik", "Popust polno pakiranje", "Vrednostni rabat", "Rabat prag 1",
    "Rabat % 1", "Rabat prag 2", "Rabat % 2", "Rabat prag 3", "Rabat % 3",
    "B2B+", "Skupine popustov", "Popust NW"
  ];

  public static Dictionary<string, string?> EmptyProductRow()
    => Empty(ProductHeaders);

  public static Dictionary<string, string?> EmptyCustomerRow()
    => Empty(CustomerHeaders);

  private static Dictionary<string, string?> Empty(IEnumerable<string> headers)
  {
    var values = new Dictionary<string, string?>(StringComparer.Ordinal);
    foreach (var header in headers) values[header] = null;
    return values;
  }
}
