/*
  092 — drevo kategorij videlektro.

  Odlocitev uporabnika 2026-08-24: "Elektro material se mora dobiti kategorije, te bodo za enkrat
  na videlektro prsle in moramo jih se vnesti v PIM. Nacelom lahko iz te strani
  https://www.videlektro.com/sl/ pregledas kako so kategorije in jih prenesel v PIM."

  Do zdaj je canon.WebSite imel stiri vrstice, drevo svetila_si 132 kategorij, drevo videlektro
  pa 0. Posledice so bile tri: stolpca 26 in 27 Magento izvoza ("Kategorije vid") sta bila prazna,
  profil WEB_videlektro je imel 0 veljavnih artiklov pri Ediitu, po migraciji 091 pa se cetrta —
  drevo brez kategorij je iz preslikave namenoma izpusceno, zato Braytronov elektromaterial ni
  imel kam.

  Vir: navigacija https://www.videlektro.com/sl/ , brana 2026-08-24. Imena ravni 2 so preverjena
  na straneh oddelkov (Instalacije, Razsvetljava), raven 3 pri Sijalkah — ujemanje je bilo tocno.

  Struktura: 5 oddelkov, 20 kategorij druge ravni, 52 tretje — skupaj 77.

  Kljuc kategorije je zapisan enako kot pri svetila_si (mala crka, brez sumnikov, presledek je
  podcrtaj, ravni loci "___"), da ga map.CategoryPathMap obravnava po isti poti.

  NAMENOMA NI vzeto s strani: OUTLET, ALL BLACK in AKCIJA. To niso kategorije izdelka, ampak
  prodajni sklopi; ce jih uporabnik hoce v drevesu, so tri vrstice.

  Angleska imena so PREDLOG in ne prevod iz vira — spletna stran je samo slovenska. Zapisana so,
  ker stolpec 26 zahteva anglesko pot; uporabnik jih sme popraviti, brez posledic za podatke,
  saj noben izdelek se nima kategorije v tem drevesu (preslikav dobaviteljev vanj se ni).
*/

SET XACT_ABORT ON;

MERGE canon.Category AS target
USING (VALUES
  (N'instalacije',NULL,1,N'Inštalacije',N'Inštalacije',1),
  (N'instalacije___kabli_in_vodniki',N'instalacije',2,N'Kabli in vodniki',N'Inštalacije > Kabli in vodniki',1),
  (N'instalacije___kabli_in_vodniki___kabelski_spojni_material',N'instalacije___kabli_in_vodniki',3,N'Kabelski spojni material',N'Inštalacije > Kabli in vodniki > Kabelski spojni material',1),
  (N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke',N'instalacije___kabli_in_vodniki',3,N'Kabelski spoji in zalivke',N'Inštalacije > Kabli in vodniki > Kabelski spoji in zalivke',1),
  (N'instalacije___kabli_in_vodniki___kabelski_koncniki_in_spojke',N'instalacije___kabli_in_vodniki',3,N'Kabelski končniki in spojke',N'Inštalacije > Kabli in vodniki > Kabelski končniki in spojke',1),
  (N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci',N'instalacije___kabli_in_vodniki',3,N'Podaljški in razdelilci',N'Inštalacije > Kabli in vodniki > Podaljški in razdelilci',1),
  (N'instalacije___kabli_in_vodniki___okovi',N'instalacije___kabli_in_vodniki',3,N'Okovi',N'Inštalacije > Kabli in vodniki > Okovi',1),
  (N'instalacije___stikala_in_vticnice',N'instalacije',2,N'Stikala in vtičnice',N'Inštalacije > Stikala in vtičnice',1),
  (N'instalacije___stikala_in_vticnice___klasicni_program',N'instalacije___stikala_in_vticnice',3,N'Klasični program',N'Inštalacije > Stikala in vtičnice > Klasični program',1),
  (N'instalacije___stikala_in_vticnice___modularni_program',N'instalacije___stikala_in_vticnice',3,N'Modularni program',N'Inštalacije > Stikala in vtičnice > Modularni program',1),
  (N'instalacije___stikala_in_vticnice___zvonci',N'instalacije___stikala_in_vticnice',3,N'Zvonci',N'Inštalacije > Stikala in vtičnice > Zvonci',1),
  (N'instalacije___prikljucni_in_pritrdilni_material',N'instalacije',2,N'Priključni in pritrdilni material',N'Inštalacije > Priključni in pritrdilni material',1),
  (N'instalacije___prikljucni_in_pritrdilni_material___uvodnice',N'instalacije___prikljucni_in_pritrdilni_material',3,N'Uvodnice',N'Inštalacije > Priključni in pritrdilni material > Uvodnice',1),
  (N'instalacije___prikljucni_in_pritrdilni_material___vezice',N'instalacije___prikljucni_in_pritrdilni_material',3,N'Vezice',N'Inštalacije > Priključni in pritrdilni material > Vezice',1),
  (N'instalacije___prikljucni_in_pritrdilni_material___objemke',N'instalacije___prikljucni_in_pritrdilni_material',3,N'Objemke',N'Inštalacije > Priključni in pritrdilni material > Objemke',1),
  (N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi',N'instalacije___prikljucni_in_pritrdilni_material',3,N'Izolirni trakovi',N'Inštalacije > Priključni in pritrdilni material > Izolirni trakovi',1),
  (N'instalacije___strelovod_in_ozemljitev',N'instalacije',2,N'Strelovod in ozemljitev',N'Inštalacije > Strelovod in ozemljitev',1),
  (N'instalacije___razvodne_doze',N'instalacije',2,N'Razvodne doze',N'Inštalacije > Razvodne doze',1),
  (N'instalacije___elektro_omare_in_razdelilniki',N'instalacije',2,N'Elektro omare in razdelilniki',N'Inštalacije > Elektro omare in razdelilniki',1),
  (N'instalacije___vtikaci_in_vticnice',N'instalacije',2,N'Vtikači in vtičnice',N'Inštalacije > Vtikači in vtičnice',1),
  (N'instalacije___instalacijski_kanali',N'instalacije',2,N'Inštalacijski kanali',N'Inštalacije > Inštalacijski kanali',1),
  (N'instalacije___omare_in_stikalna_tehnika',N'instalacije',2,N'Omare in stikalna tehnika',N'Inštalacije > Omare in stikalna tehnika',1),
  (N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki',N'instalacije___omare_in_stikalna_tehnika',3,N'Inštalacijski odklopniki',N'Inštalacije > Omare in stikalna tehnika > Inštalacijski odklopniki',1),
  (N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor',N'instalacije___omare_in_stikalna_tehnika',3,N'Zbiralke in pribor',N'Inštalacije > Omare in stikalna tehnika > Zbiralke in pribor',1),
  (N'instalacije___omare_in_stikalna_tehnika___kovinske_omare',N'instalacije___omare_in_stikalna_tehnika',3,N'Kovinske omare',N'Inštalacije > Omare in stikalna tehnika > Kovinske omare',1),
  (N'instalacije___ventilatorji',N'instalacije',2,N'Ventilatorji',N'Inštalacije > Ventilatorji',1),
  (N'razsvetljava',NULL,1,N'Razsvetljava',N'Razsvetljava',1),
  (N'razsvetljava___luci',N'razsvetljava',2,N'Luči',N'Razsvetljava > Luči',1),
  (N'razsvetljava___luci___zunanje_luci',N'razsvetljava___luci',3,N'Zunanje luči',N'Razsvetljava > Luči > Zunanje luči',1),
  (N'razsvetljava___luci___stropne_luci',N'razsvetljava___luci',3,N'Stropne luči',N'Razsvetljava > Luči > Stropne luči',1),
  (N'razsvetljava___luci___stenske_luci',N'razsvetljava___luci',3,N'Stenske luči',N'Razsvetljava > Luči > Stenske luči',1),
  (N'razsvetljava___luci___stojece_luci',N'razsvetljava___luci',3,N'Stoječe luči',N'Razsvetljava > Luči > Stoječe luči',1),
  (N'razsvetljava___luci___namizne_luci',N'razsvetljava___luci',3,N'Namizne luči',N'Razsvetljava > Luči > Namizne luči',1),
  (N'razsvetljava___luci___reflektorji',N'razsvetljava___luci',3,N'Reflektorji',N'Razsvetljava > Luči > Reflektorji',1),
  (N'razsvetljava___luci___zasilna_razsvetljava',N'razsvetljava___luci',3,N'Zasilna razsvetljava',N'Razsvetljava > Luči > Zasilna razsvetljava',1),
  (N'razsvetljava___luci___prahotesne_svetilke',N'razsvetljava___luci',3,N'Prahotesne svetilke',N'Razsvetljava > Luči > Prahotesne svetilke',1),
  (N'razsvetljava___luci___high_bay_svetila',N'razsvetljava___luci',3,N'High bay svetila',N'Razsvetljava > Luči > High bay svetila',1),
  (N'razsvetljava___luci___okovi',N'razsvetljava___luci',3,N'Okovi',N'Razsvetljava > Luči > Okovi',1),
  (N'razsvetljava___luci___cameleon_sistem',N'razsvetljava___luci',3,N'Cameleon sistem',N'Razsvetljava > Luči > Cameleon sistem',1),
  (N'razsvetljava___luci___dodatki',N'razsvetljava___luci',3,N'Dodatki',N'Razsvetljava > Luči > Dodatki',1),
  (N'razsvetljava___sijalke',N'razsvetljava',2,N'Sijalke',N'Razsvetljava > Sijalke',1),
  (N'razsvetljava___sijalke___led_sijalke_e27',N'razsvetljava___sijalke',3,N'LED sijalke E27',N'Razsvetljava > Sijalke > LED sijalke E27',1),
  (N'razsvetljava___sijalke___led_sijalke_e14',N'razsvetljava___sijalke',3,N'LED sijalke E14',N'Razsvetljava > Sijalke > LED sijalke E14',1),
  (N'razsvetljava___sijalke___led_sijalke_g9',N'razsvetljava___sijalke',3,N'LED sijalke G9',N'Razsvetljava > Sijalke > LED sijalke G9',1),
  (N'razsvetljava___sijalke___led_sijalke_gu10',N'razsvetljava___sijalke',3,N'LED sijalke GU10',N'Razsvetljava > Sijalke > LED sijalke GU10',1),
  (N'razsvetljava___sijalke___led_cevi_t8_g13',N'razsvetljava___sijalke',3,N'LED cevi T8-G13',N'Razsvetljava > Sijalke > LED cevi T8-G13',1),
  (N'razsvetljava___sijalke___led_sijalke_gu5_3',N'razsvetljava___sijalke',3,N'LED sijalke GU5.3',N'Razsvetljava > Sijalke > LED sijalke GU5.3',1),
  (N'razsvetljava___sijalke___led_sijalke_r7',N'razsvetljava___sijalke',3,N'LED sijalke R7',N'Razsvetljava > Sijalke > LED sijalke R7',1),
  (N'razsvetljava___sijalke___led_sijalke_gx53',N'razsvetljava___sijalke',3,N'LED sijalke GX53',N'Razsvetljava > Sijalke > LED sijalke GX53',1),
  (N'razsvetljava___sijalke___led_sijalke_g4',N'razsvetljava___sijalke',3,N'LED sijalke G4',N'Razsvetljava > Sijalke > LED sijalke G4',1),
  (N'razsvetljava___sijalke___retro_sijalke',N'razsvetljava___sijalke',3,N'Retro sijalke',N'Razsvetljava > Sijalke > Retro sijalke',1),
  (N'razsvetljava___led_trakovi_in_profili',N'razsvetljava',2,N'LED trakovi in profili',N'Razsvetljava > LED trakovi in profili',1),
  (N'razsvetljava___led_trakovi_in_profili___led_trakovi',N'razsvetljava___led_trakovi_in_profili',3,N'LED trakovi',N'Razsvetljava > LED trakovi in profili > LED trakovi',1),
  (N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki',N'razsvetljava___led_trakovi_in_profili',3,N'LED profili in dodatki',N'Razsvetljava > LED trakovi in profili > LED profili in dodatki',1),
  (N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki',N'razsvetljava___led_trakovi_in_profili',3,N'Kontrolerji in zatemnilniki',N'Razsvetljava > LED trakovi in profili > Kontrolerji in zatemnilniki',1),
  (N'razsvetljava___led_trakovi_in_profili___napajalniki',N'razsvetljava___led_trakovi_in_profili',3,N'Napajalniki',N'Razsvetljava > LED trakovi in profili > Napajalniki',1),
  (N'razsvetljava___led_trakovi_in_profili___kabli_in_konektorji',N'razsvetljava___led_trakovi_in_profili',3,N'Kabli in konektorji',N'Razsvetljava > LED trakovi in profili > Kabli in konektorji',1),
  (N'razsvetljava___senzorji_gibanja',N'razsvetljava',2,N'Senzorji gibanja',N'Razsvetljava > Senzorji gibanja',1),
  (N'razsvetljava___senzorji_gibanja___senzorji',N'razsvetljava___senzorji_gibanja',3,N'Senzorji',N'Razsvetljava > Senzorji gibanja > Senzorji',1),
  (N'razsvetljava___senzorji_gibanja___dodatki_k_senzorjem',N'razsvetljava___senzorji_gibanja',3,N'Dodatki k senzorjem',N'Razsvetljava > Senzorji gibanja > Dodatki k senzorjem',1),
  (N'razsvetljava___upravljanje_in_nadzor',N'razsvetljava',2,N'Upravljanje in nadzor',N'Razsvetljava > Upravljanje in nadzor',1),
  (N'razsvetljava___tracni_sistemi',N'razsvetljava',2,N'Tračni sistemi',N'Razsvetljava > Tračni sistemi',1),
  (N'razsvetljava___tracni_sistemi___enofazni',N'razsvetljava___tracni_sistemi',3,N'Enofazni',N'Razsvetljava > Tračni sistemi > Enofazni',1),
  (N'razsvetljava___tracni_sistemi___trofazni',N'razsvetljava___tracni_sistemi',3,N'Trofazni',N'Razsvetljava > Tračni sistemi > Trofazni',1),
  (N'razsvetljava___tracni_sistemi___magnetni',N'razsvetljava___tracni_sistemi',3,N'Magnetni',N'Razsvetljava > Tračni sistemi > Magnetni',1),
  (N'orodje',NULL,1,N'Orodje',N'Orodje',1),
  (N'orodje___rocno_orodje',N'orodje',2,N'Ročno orodje',N'Orodje > Ročno orodje',1),
  (N'orodje___rocno_orodje___predvleke',N'orodje___rocno_orodje',3,N'Predvleke',N'Orodje > Ročno orodje > Predvleke',1),
  (N'orodje___rocno_orodje___ostalo_orodje',N'orodje___rocno_orodje',3,N'Ostalo orodje',N'Orodje > Ročno orodje > Ostalo orodje',1),
  (N'orodje___prenosni_merilni_instrumenti',N'orodje',2,N'Prenosni merilni inštrumenti',N'Orodje > Prenosni merilni inštrumenti',1),
  (N'orodje___elektricno_orodje',N'orodje',2,N'Električno orodje',N'Orodje > Električno orodje',1),
  (N'e_mobility',NULL,1,N'E-mobility',N'E-mobility',1),
  (N'e_mobility___elektricne_polnilnice',N'e_mobility',2,N'Električne polnilnice',N'E-mobility > Električne polnilnice',1),
  (N'e_mobility___elektricne_polnilnice___polnilnice',N'e_mobility___elektricne_polnilnice',3,N'Polnilnice',N'E-mobility > Električne polnilnice > Polnilnice',1),
  (N'e_mobility___elektricne_polnilnice___nadgradnje',N'e_mobility___elektricne_polnilnice',3,N'Nadgradnje',N'E-mobility > Električne polnilnice > Nadgradnje',1),
  (N'e_mobility___elektricne_polnilnice___dodatna_oprema',N'e_mobility___elektricne_polnilnice',3,N'Dodatna oprema',N'E-mobility > Električne polnilnice > Dodatna oprema',1),
  (N'alarmni_sistemi',NULL,1,N'Alarmni sistemi',N'Alarmni sistemi',1)
) AS source(CategoryCode,ParentCategoryCode,LevelNo,CategoryName,CategoryPath,IsActive)
  ON target.CategoryTreeCode = N'videlektro' AND target.CategoryCode = source.CategoryCode
WHEN MATCHED THEN UPDATE SET
  ParentCategoryCode = source.ParentCategoryCode, LevelNo = source.LevelNo,
  CategoryName = source.CategoryName, CategoryPath = source.CategoryPath, IsActive = source.IsActive
WHEN NOT MATCHED THEN INSERT (CategoryTreeCode,CategoryCode,ParentCategoryCode,LevelNo,CategoryName,CategoryPath,IsActive)
  VALUES (N'videlektro',source.CategoryCode,source.ParentCategoryCode,source.LevelNo,source.CategoryName,source.CategoryPath,source.IsActive);

MERGE canon.CategoryTranslation AS target
USING (VALUES
  (N'instalacije',N'sl',N'Inštalacije'),
  (N'instalacije',N'en',N'Installations'),
  (N'instalacije___kabli_in_vodniki',N'sl',N'Kabli in vodniki'),
  (N'instalacije___kabli_in_vodniki',N'en',N'Cables and Wires'),
  (N'instalacije___kabli_in_vodniki___kabelski_spojni_material',N'sl',N'Kabelski spojni material'),
  (N'instalacije___kabli_in_vodniki___kabelski_spojni_material',N'en',N'Cable Jointing Material'),
  (N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke',N'sl',N'Kabelski spoji in zalivke'),
  (N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke',N'en',N'Cable Joints and Resins'),
  (N'instalacije___kabli_in_vodniki___kabelski_koncniki_in_spojke',N'sl',N'Kabelski končniki in spojke'),
  (N'instalacije___kabli_in_vodniki___kabelski_koncniki_in_spojke',N'en',N'Cable Terminals and Connectors'),
  (N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci',N'sl',N'Podaljški in razdelilci'),
  (N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci',N'en',N'Extension Leads and Splitters'),
  (N'instalacije___kabli_in_vodniki___okovi',N'sl',N'Okovi'),
  (N'instalacije___kabli_in_vodniki___okovi',N'en',N'Lampholders'),
  (N'instalacije___stikala_in_vticnice',N'sl',N'Stikala in vtičnice'),
  (N'instalacije___stikala_in_vticnice',N'en',N'Switches and Sockets'),
  (N'instalacije___stikala_in_vticnice___klasicni_program',N'sl',N'Klasični program'),
  (N'instalacije___stikala_in_vticnice___klasicni_program',N'en',N'Classic Range'),
  (N'instalacije___stikala_in_vticnice___modularni_program',N'sl',N'Modularni program'),
  (N'instalacije___stikala_in_vticnice___modularni_program',N'en',N'Modular Range'),
  (N'instalacije___stikala_in_vticnice___zvonci',N'sl',N'Zvonci'),
  (N'instalacije___stikala_in_vticnice___zvonci',N'en',N'Doorbells'),
  (N'instalacije___prikljucni_in_pritrdilni_material',N'sl',N'Priključni in pritrdilni material'),
  (N'instalacije___prikljucni_in_pritrdilni_material',N'en',N'Connection and Fastening Material'),
  (N'instalacije___prikljucni_in_pritrdilni_material___uvodnice',N'sl',N'Uvodnice'),
  (N'instalacije___prikljucni_in_pritrdilni_material___uvodnice',N'en',N'Cable Glands'),
  (N'instalacije___prikljucni_in_pritrdilni_material___vezice',N'sl',N'Vezice'),
  (N'instalacije___prikljucni_in_pritrdilni_material___vezice',N'en',N'Cable Ties'),
  (N'instalacije___prikljucni_in_pritrdilni_material___objemke',N'sl',N'Objemke'),
  (N'instalacije___prikljucni_in_pritrdilni_material___objemke',N'en',N'Clamps'),
  (N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi',N'sl',N'Izolirni trakovi'),
  (N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi',N'en',N'Insulating Tapes'),
  (N'instalacije___strelovod_in_ozemljitev',N'sl',N'Strelovod in ozemljitev'),
  (N'instalacije___strelovod_in_ozemljitev',N'en',N'Lightning Protection and Earthing'),
  (N'instalacije___razvodne_doze',N'sl',N'Razvodne doze'),
  (N'instalacije___razvodne_doze',N'en',N'Junction Boxes'),
  (N'instalacije___elektro_omare_in_razdelilniki',N'sl',N'Elektro omare in razdelilniki'),
  (N'instalacije___elektro_omare_in_razdelilniki',N'en',N'Electrical Cabinets and Distribution Boards'),
  (N'instalacije___vtikaci_in_vticnice',N'sl',N'Vtikači in vtičnice'),
  (N'instalacije___vtikaci_in_vticnice',N'en',N'Plugs and Sockets'),
  (N'instalacije___instalacijski_kanali',N'sl',N'Inštalacijski kanali'),
  (N'instalacije___instalacijski_kanali',N'en',N'Trunking'),
  (N'instalacije___omare_in_stikalna_tehnika',N'sl',N'Omare in stikalna tehnika'),
  (N'instalacije___omare_in_stikalna_tehnika',N'en',N'Enclosures and Switchgear'),
  (N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki',N'sl',N'Inštalacijski odklopniki'),
  (N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki',N'en',N'Miniature Circuit Breakers'),
  (N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor',N'sl',N'Zbiralke in pribor'),
  (N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor',N'en',N'Busbars and Accessories'),
  (N'instalacije___omare_in_stikalna_tehnika___kovinske_omare',N'sl',N'Kovinske omare'),
  (N'instalacije___omare_in_stikalna_tehnika___kovinske_omare',N'en',N'Metal Enclosures'),
  (N'instalacije___ventilatorji',N'sl',N'Ventilatorji'),
  (N'instalacije___ventilatorji',N'en',N'Fans'),
  (N'razsvetljava',N'sl',N'Razsvetljava'),
  (N'razsvetljava',N'en',N'Lighting'),
  (N'razsvetljava___luci',N'sl',N'Luči'),
  (N'razsvetljava___luci',N'en',N'Luminaires'),
  (N'razsvetljava___luci___zunanje_luci',N'sl',N'Zunanje luči'),
  (N'razsvetljava___luci___zunanje_luci',N'en',N'Outdoor Luminaires'),
  (N'razsvetljava___luci___stropne_luci',N'sl',N'Stropne luči'),
  (N'razsvetljava___luci___stropne_luci',N'en',N'Ceiling Luminaires'),
  (N'razsvetljava___luci___stenske_luci',N'sl',N'Stenske luči'),
  (N'razsvetljava___luci___stenske_luci',N'en',N'Wall Luminaires'),
  (N'razsvetljava___luci___stojece_luci',N'sl',N'Stoječe luči'),
  (N'razsvetljava___luci___stojece_luci',N'en',N'Floor Luminaires'),
  (N'razsvetljava___luci___namizne_luci',N'sl',N'Namizne luči'),
  (N'razsvetljava___luci___namizne_luci',N'en',N'Table Luminaires'),
  (N'razsvetljava___luci___reflektorji',N'sl',N'Reflektorji'),
  (N'razsvetljava___luci___reflektorji',N'en',N'Floodlights'),
  (N'razsvetljava___luci___zasilna_razsvetljava',N'sl',N'Zasilna razsvetljava'),
  (N'razsvetljava___luci___zasilna_razsvetljava',N'en',N'Emergency Lighting'),
  (N'razsvetljava___luci___prahotesne_svetilke',N'sl',N'Prahotesne svetilke'),
  (N'razsvetljava___luci___prahotesne_svetilke',N'en',N'Dustproof Luminaires'),
  (N'razsvetljava___luci___high_bay_svetila',N'sl',N'High bay svetila'),
  (N'razsvetljava___luci___high_bay_svetila',N'en',N'High Bay Luminaires'),
  (N'razsvetljava___luci___okovi',N'sl',N'Okovi'),
  (N'razsvetljava___luci___okovi',N'en',N'Lampholders'),
  (N'razsvetljava___luci___cameleon_sistem',N'sl',N'Cameleon sistem'),
  (N'razsvetljava___luci___cameleon_sistem',N'en',N'Cameleon System'),
  (N'razsvetljava___luci___dodatki',N'sl',N'Dodatki'),
  (N'razsvetljava___luci___dodatki',N'en',N'Accessories'),
  (N'razsvetljava___sijalke',N'sl',N'Sijalke'),
  (N'razsvetljava___sijalke',N'en',N'Bulbs'),
  (N'razsvetljava___sijalke___led_sijalke_e27',N'sl',N'LED sijalke E27'),
  (N'razsvetljava___sijalke___led_sijalke_e27',N'en',N'LED Bulbs E27'),
  (N'razsvetljava___sijalke___led_sijalke_e14',N'sl',N'LED sijalke E14'),
  (N'razsvetljava___sijalke___led_sijalke_e14',N'en',N'LED Bulbs E14'),
  (N'razsvetljava___sijalke___led_sijalke_g9',N'sl',N'LED sijalke G9'),
  (N'razsvetljava___sijalke___led_sijalke_g9',N'en',N'LED Bulbs G9'),
  (N'razsvetljava___sijalke___led_sijalke_gu10',N'sl',N'LED sijalke GU10'),
  (N'razsvetljava___sijalke___led_sijalke_gu10',N'en',N'LED Bulbs GU10'),
  (N'razsvetljava___sijalke___led_cevi_t8_g13',N'sl',N'LED cevi T8-G13'),
  (N'razsvetljava___sijalke___led_cevi_t8_g13',N'en',N'LED Tubes T8-G13'),
  (N'razsvetljava___sijalke___led_sijalke_gu5_3',N'sl',N'LED sijalke GU5.3'),
  (N'razsvetljava___sijalke___led_sijalke_gu5_3',N'en',N'LED Bulbs GU5.3'),
  (N'razsvetljava___sijalke___led_sijalke_r7',N'sl',N'LED sijalke R7'),
  (N'razsvetljava___sijalke___led_sijalke_r7',N'en',N'LED Bulbs R7'),
  (N'razsvetljava___sijalke___led_sijalke_gx53',N'sl',N'LED sijalke GX53'),
  (N'razsvetljava___sijalke___led_sijalke_gx53',N'en',N'LED Bulbs GX53'),
  (N'razsvetljava___sijalke___led_sijalke_g4',N'sl',N'LED sijalke G4'),
  (N'razsvetljava___sijalke___led_sijalke_g4',N'en',N'LED Bulbs G4'),
  (N'razsvetljava___sijalke___retro_sijalke',N'sl',N'Retro sijalke'),
  (N'razsvetljava___sijalke___retro_sijalke',N'en',N'Retro Bulbs'),
  (N'razsvetljava___led_trakovi_in_profili',N'sl',N'LED trakovi in profili'),
  (N'razsvetljava___led_trakovi_in_profili',N'en',N'LED Strips and Profiles'),
  (N'razsvetljava___led_trakovi_in_profili___led_trakovi',N'sl',N'LED trakovi'),
  (N'razsvetljava___led_trakovi_in_profili___led_trakovi',N'en',N'LED Strips'),
  (N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki',N'sl',N'LED profili in dodatki'),
  (N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki',N'en',N'LED Profiles and Accessories'),
  (N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki',N'sl',N'Kontrolerji in zatemnilniki'),
  (N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki',N'en',N'Controllers and Dimmers'),
  (N'razsvetljava___led_trakovi_in_profili___napajalniki',N'sl',N'Napajalniki'),
  (N'razsvetljava___led_trakovi_in_profili___napajalniki',N'en',N'Power Supplies'),
  (N'razsvetljava___led_trakovi_in_profili___kabli_in_konektorji',N'sl',N'Kabli in konektorji'),
  (N'razsvetljava___led_trakovi_in_profili___kabli_in_konektorji',N'en',N'Cables and Connectors'),
  (N'razsvetljava___senzorji_gibanja',N'sl',N'Senzorji gibanja'),
  (N'razsvetljava___senzorji_gibanja',N'en',N'Motion Sensors'),
  (N'razsvetljava___senzorji_gibanja___senzorji',N'sl',N'Senzorji'),
  (N'razsvetljava___senzorji_gibanja___senzorji',N'en',N'Sensors'),
  (N'razsvetljava___senzorji_gibanja___dodatki_k_senzorjem',N'sl',N'Dodatki k senzorjem'),
  (N'razsvetljava___senzorji_gibanja___dodatki_k_senzorjem',N'en',N'Sensor Accessories'),
  (N'razsvetljava___upravljanje_in_nadzor',N'sl',N'Upravljanje in nadzor'),
  (N'razsvetljava___upravljanje_in_nadzor',N'en',N'Control and Monitoring'),
  (N'razsvetljava___tracni_sistemi',N'sl',N'Tračni sistemi'),
  (N'razsvetljava___tracni_sistemi',N'en',N'Track Systems'),
  (N'razsvetljava___tracni_sistemi___enofazni',N'sl',N'Enofazni'),
  (N'razsvetljava___tracni_sistemi___enofazni',N'en',N'Single-phase'),
  (N'razsvetljava___tracni_sistemi___trofazni',N'sl',N'Trofazni'),
  (N'razsvetljava___tracni_sistemi___trofazni',N'en',N'Three-phase'),
  (N'razsvetljava___tracni_sistemi___magnetni',N'sl',N'Magnetni'),
  (N'razsvetljava___tracni_sistemi___magnetni',N'en',N'Magnetic'),
  (N'orodje',N'sl',N'Orodje'),
  (N'orodje',N'en',N'Tools'),
  (N'orodje___rocno_orodje',N'sl',N'Ročno orodje'),
  (N'orodje___rocno_orodje',N'en',N'Hand Tools'),
  (N'orodje___rocno_orodje___predvleke',N'sl',N'Predvleke'),
  (N'orodje___rocno_orodje___predvleke',N'en',N'Draw Tapes'),
  (N'orodje___rocno_orodje___ostalo_orodje',N'sl',N'Ostalo orodje'),
  (N'orodje___rocno_orodje___ostalo_orodje',N'en',N'Other Tools'),
  (N'orodje___prenosni_merilni_instrumenti',N'sl',N'Prenosni merilni inštrumenti'),
  (N'orodje___prenosni_merilni_instrumenti',N'en',N'Portable Measuring Instruments'),
  (N'orodje___elektricno_orodje',N'sl',N'Električno orodje'),
  (N'orodje___elektricno_orodje',N'en',N'Power Tools'),
  (N'e_mobility',N'sl',N'E-mobility'),
  (N'e_mobility',N'en',N'E-mobility'),
  (N'e_mobility___elektricne_polnilnice',N'sl',N'Električne polnilnice'),
  (N'e_mobility___elektricne_polnilnice',N'en',N'EV Charging Stations'),
  (N'e_mobility___elektricne_polnilnice___polnilnice',N'sl',N'Polnilnice'),
  (N'e_mobility___elektricne_polnilnice___polnilnice',N'en',N'Chargers'),
  (N'e_mobility___elektricne_polnilnice___nadgradnje',N'sl',N'Nadgradnje'),
  (N'e_mobility___elektricne_polnilnice___nadgradnje',N'en',N'Upgrades'),
  (N'e_mobility___elektricne_polnilnice___dodatna_oprema',N'sl',N'Dodatna oprema'),
  (N'e_mobility___elektricne_polnilnice___dodatna_oprema',N'en',N'Additional Equipment'),
  (N'alarmni_sistemi',N'sl',N'Alarmni sistemi'),
  (N'alarmni_sistemi',N'en',N'Alarm Systems')
) AS source(CategoryCode,LanguageCode,CategoryName)
  ON target.CategoryTreeCode = N'videlektro' AND target.CategoryCode = source.CategoryCode
    AND target.LanguageCode = source.LanguageCode
WHEN MATCHED THEN UPDATE SET CategoryName = source.CategoryName
WHEN NOT MATCHED THEN INSERT (CategoryTreeCode,CategoryCode,LanguageCode,CategoryName)
  VALUES (N'videlektro',source.CategoryCode,source.LanguageCode,source.CategoryName);
