/*
  173 — nabori atributov po kategorijah iz mastrov starega PIM-a (uporabnik 2026-09-08: "preberi mastre
  iz PIM_test in napolni nabore").

  Vir: ..\PIM_test\Mastri\_Pregled_atributov_po_kategorijah.xlsx, list Matrika (923 atributov x 53
  mastrov z odstotkom zasedenosti), prek generiranega izpisa
  ..\PIM_test\sql\migrations\tools\Seed_CategoryAttributeImport_Mastri.sql (prag 50 %, 1058 parov,
  358 razlicnih imen). Stari sistem preslikave ni nikoli naredil (pim.CategoryAttributeMap,
  pim.AttributeAlias in pim.CategoryExternalMap MASTRI so prazni); preslikava je narejena tu in je
  opisana v docs/NABORI_ATRIBUTOV_IZ_MASTROV.md:

    - master -> kategorija: elektro mastri (1xx) v drevo videlektro, mastri svetil (2xx) v svetila_si
      in ustrezno vejo videlektro/razsvetljava; mastri po blagovnih znamkah (2A1, 2A5-2A10, 2A13) so
      zdruzeni v skupni nabor korenov notranja_svetila, zunanja_svetila in razsvetljava___luci
      (atribut, ki je >= 50 % zaseden v vsaj dveh znamkah; zasedenost = povprecje).
    - ime v Matriki -> koda registra: enako ime (brez sumnikov, velikosti crk) ali izrecen alias
      (npr. "IP zascita" -> IP_STOPNJA_ZASCITE, "Kot svetenja" -> KOT_SVETLOBNEGA_SNOPA). Ujetih 483
      od 1058 parov; neujeto so vecinoma polja izdelka (Proizvajalec, Tip, Kljucne besede, nazivi
      za nalepke), ne atributi. Register se NE siri; kar v njem ne obstaja, ni v naboru.
    - raven: REQUIRED, kadar je zasedenost v mastru >= 95 % IN (v poddrevesu ni izdelkov ALI ima
      vrednost >= 90 % izdelkov, merjeno 2026-09-08 na razvojni bazi), sicer RECOMMENDED. Tako
      obvezni atributi danes blokirajo natanko 4 izdelke (tracni_sistemi / Prevladujoca barva);
      vse ostalo je opozorilo. Ravni so tu ZAPISANE kot vrednosti in se ne racunajo znova, da je
      migracija enaka v vsakem okolju.

  Vrstic: 484 (209 obveznih, 275 priporocenih) v 46 kategorijah.
  Gre skozi canon.SaveCategoryAttributeSetBulk (170) -> canon.SaveCategoryAttributeSet (147): zahteve
  spletnih profilov in revizija nastanejo tam. Ponoven zagon isto vrstico posodobi, ne podvoji.
  Rocno spremenjene aktivne vrstice (UpdatedBy <> 'mastri 2026-09-08') ta migracija ne prepise.
*/

SET XACT_ABORT ON;

DECLARE @Seed TABLE (Seq int IDENTITY(1,1) PRIMARY KEY, CategoryTreeCode nvarchar(100), CategoryCode nvarchar(200),
  AttributeCode nvarchar(200), Level nvarchar(20), FillPct int, Masters nvarchar(400));
INSERT @Seed (CategoryTreeCode, CategoryCode, AttributeCode, Level, FillPct, Masters) VALUES
  (N'svetila_si', N'notranja_svetila', N'DOLZINA', N'RECOMMENDED', 86, N'znamke:2A1+2A13'),
  (N'svetila_si', N'notranja_svetila', N'FREKVENCA', N'RECOMMENDED', 90, N'znamke:2A7+2A6'),
  (N'svetila_si', N'notranja_svetila', N'GARANCIJA', N'RECOMMENDED', 91, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'notranja_svetila', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 70, N'znamke:2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'notranja_svetila', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 91, N'znamke:2A1+2A10+2A13+2A6+2A7+2A9'),
  (N'svetila_si', N'notranja_svetila', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 58, N'znamke:2A1+2A6'),
  (N'svetila_si', N'notranja_svetila', N'NACIN_MONTAZE', N'RECOMMENDED', 89, N'znamke:2A1+2A6+2A7+2A9+2A7'),
  (N'svetila_si', N'notranja_svetila', N'NAPETOST', N'RECOMMENDED', 89, N'znamke:2A1+2A6+2A7+2A1+2A6+2A7+2A7'),
  (N'svetila_si', N'notranja_svetila', N'NAZIVNA_MOC', N'RECOMMENDED', 77, N'znamke:2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'notranja_svetila', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 96, N'znamke:2A1+2A6'),
  (N'svetila_si', N'notranja_svetila', N'OBLIKA_SVETILKE', N'RECOMMENDED', 83, N'znamke:2A1+2A6+2A9+2A5+2A7+2A9+2A6+2A5'),
  (N'svetila_si', N'notranja_svetila', N'PREVLADUJOC_MATERIAL', N'RECOMMENDED', 90, N'znamke:2A1+2A5+2A6+2A7+2A9+2A13'),
  (N'svetila_si', N'notranja_svetila', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 90, N'znamke:2A1+2A10+2A13+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'notranja_svetila', N'SENZOR_GIBANJA', N'RECOMMENDED', 93, N'znamke:2A1+2A6+2A9'),
  (N'svetila_si', N'notranja_svetila', N'SIRINA', N'RECOMMENDED', 70, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'notranja_svetila', N'SLOG', N'RECOMMENDED', 77, N'znamke:2A1+2A10+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'notranja_svetila', N'SVETLOBNI_TOK', N'RECOMMENDED', 73, N'znamke:2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'notranja_svetila', N'TEMPERATURA_BARVE', N'RECOMMENDED', 76, N'znamke:2A1+2A6+2A9+2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'notranja_svetila', N'UPORABA', N'RECOMMENDED', 92, N'znamke:2A1+2A6+2A9'),
  (N'svetila_si', N'notranja_svetila', N'VISINA', N'RECOMMENDED', 84, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'notranja_svetila', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 79, N'znamke:2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'notranja_svetila', N'ZATEMNLJIVO', N'RECOMMENDED', 92, N'znamke:2A1+2A6+2A7+2A9'),
  (N'svetila_si', N'notranja_svetila', N'ZIVLJENJSKA_DOBA', N'RECOMMENDED', 79, N'znamke:2A1+2A13+2A6'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'DOLZINA', N'RECOMMENDED', 71, N'2A15'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 53, N'2A15'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'NACIN_MONTAZE', N'RECOMMENDED', 90, N'2A15'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'OBLIKA_SVETILKE', N'RECOMMENDED', 76, N'2A15'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'PREVLADUJOC_MATERIAL', N'RECOMMENDED', 61, N'2A15'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 85, N'2A15'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'SIRINA', N'RECOMMENDED', 86, N'2A15'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'UPORABA', N'RECOMMENDED', 100, N'2A15'),
  (N'svetila_si', N'notranja_svetila___dodatki', N'VISINA', N'RECOMMENDED', 86, N'2A15'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'EKVIVALENT', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'ENERGIJSKI_RAZRED', N'RECOMMENDED', 99, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'GARANCIJA', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'GRLO', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 99, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 99, N'2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'NAPETOST', N'RECOMMENDED', 100, N'2G1,2G2,2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'NAZIVNA_MOC', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'OBLIKA_SVETILKE', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'SENZOR_GIBANJA', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'SIRINA', N'RECOMMENDED', 99, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'SVETLOBNI_TOK', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'TEMPERATURA_BARVE', N'RECOMMENDED', 100, N'2G1,2G2,2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'VISINA', N'RECOMMENDED', 99, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 90, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'ZATEMNLJIVO', N'RECOMMENDED', 100, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki', N'ZIVLJENJSKA_DOBA', N'RECOMMENDED', 99, N'2G1,2G2'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___dodatki', N'DELOVNA_TEMPERATURA', N'RECOMMENDED', 85, N'2G3'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___dodatki', N'GRLO', N'RECOMMENDED', 100, N'2G3'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___dodatki', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 95, N'2G3'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___dodatki', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 100, N'2G3'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___dodatki', N'SIRINA', N'RECOMMENDED', 85, N'2G3'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___dodatki', N'VISINA', N'RECOMMENDED', 55, N'2G3'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___dodatki', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 95, N'2G3'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'DOLZINA', N'RECOMMENDED', 99, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'GARANCIJA', N'RECOMMENDED', 100, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'NACIN_MONTAZE', N'RECOMMENDED', 100, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'NAZIVNA_JAKOST_TOKA', N'RECOMMENDED', 99, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'NAZIVNA_MOC', N'RECOMMENDED', 100, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 100, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'SIRINA', N'RECOMMENDED', 100, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'VISINA', N'RECOMMENDED', 99, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'NAPETOST', N'REQUIRED', 100, N'2E,2E,2E'),
  (N'svetila_si', N'svetlobni_viri_in_dodatki___napajalniki', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2E'),
  (N'svetila_si', N'tracni_sistemi', N'DOLZINA', N'RECOMMENDED', 87, N'2H1'),
  (N'svetila_si', N'tracni_sistemi', N'GARANCIJA', N'RECOMMENDED', 100, N'2H1'),
  (N'svetila_si', N'tracni_sistemi', N'NACIN_MONTAZE', N'RECOMMENDED', 92, N'2H1'),
  (N'svetila_si', N'tracni_sistemi', N'SIRINA', N'RECOMMENDED', 87, N'2H1'),
  (N'svetila_si', N'tracni_sistemi', N'SLOG', N'RECOMMENDED', 100, N'2H1'),
  (N'svetila_si', N'tracni_sistemi', N'UPORABA', N'RECOMMENDED', 100, N'2H1'),
  (N'svetila_si', N'tracni_sistemi', N'VISINA', N'RECOMMENDED', 77, N'2H1'),
  (N'svetila_si', N'tracni_sistemi', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2H1'),
  (N'svetila_si', N'tracni_sistemi', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2H1,2H1'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'DOLZINA', N'RECOMMENDED', 66, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'NAZIVNA_MOC', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'SIRINA', N'RECOMMENDED', 99, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'SVETLOBNI_TOK', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'TEMPERATURA_BARVE', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'VISINA', N'RECOMMENDED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'ZDRUZLJIVO_Z', N'RECOMMENDED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'GARANCIJA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'NACIN_MONTAZE', N'REQUIRED', 100, N'2H2,2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'NAPETOST', N'REQUIRED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'SLOG', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_24v_nano_lvm___led_svetilke', N'UPORABA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'DOLZINA', N'RECOMMENDED', 66, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'NAZIVNA_MOC', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'SIRINA', N'RECOMMENDED', 99, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'SVETLOBNI_TOK', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'TEMPERATURA_BARVE', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'VISINA', N'RECOMMENDED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'ZDRUZLJIVO_Z', N'RECOMMENDED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'GARANCIJA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'NACIN_MONTAZE', N'REQUIRED', 100, N'2H2,2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'NAPETOST', N'REQUIRED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'SLOG', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_lvm___led_svetilke', N'UPORABA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'DOLZINA', N'RECOMMENDED', 66, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'NAZIVNA_MOC', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'SIRINA', N'RECOMMENDED', 99, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'SLOG', N'RECOMMENDED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'SVETLOBNI_TOK', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'TEMPERATURA_BARVE', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'UPORABA', N'RECOMMENDED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'VISINA', N'RECOMMENDED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'ZDRUZLJIVO_Z', N'RECOMMENDED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'GARANCIJA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'NACIN_MONTAZE', N'REQUIRED', 100, N'2H2,2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'NAPETOST', N'REQUIRED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_48v_ut_lvm___led_svetilke', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'DOLZINA', N'RECOMMENDED', 66, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'NAZIVNA_MOC', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'SVETLOBNI_TOK', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'TEMPERATURA_BARVE', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'GARANCIJA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'NACIN_MONTAZE', N'REQUIRED', 100, N'2H2,2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'NAPETOST', N'REQUIRED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'SIRINA', N'REQUIRED', 99, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'SLOG', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'UPORABA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'VISINA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___1_fazni_profile___svetila', N'ZDRUZLJIVO_Z', N'REQUIRED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'DOLZINA', N'RECOMMENDED', 66, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'NAZIVNA_MOC', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'SIRINA', N'RECOMMENDED', 99, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'SLOG', N'RECOMMENDED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'SVETLOBNI_TOK', N'RECOMMENDED', 81, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'TEMPERATURA_BARVE', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'UPORABA', N'RECOMMENDED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'VISINA', N'RECOMMENDED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 80, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'ZDRUZLJIVO_Z', N'RECOMMENDED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'GARANCIJA', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'NACIN_MONTAZE', N'REQUIRED', 100, N'2H2,2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'NAPETOST', N'REQUIRED', 97, N'2H2,2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2H2'),
  (N'svetila_si', N'tracni_sistemi___3_fazni_ctls___svetila', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2H2,2H2'),
  (N'svetila_si', N'zunanja_svetila', N'DOLZINA', N'RECOMMENDED', 86, N'znamke:2A1+2A13'),
  (N'svetila_si', N'zunanja_svetila', N'FREKVENCA', N'RECOMMENDED', 90, N'znamke:2A7+2A6'),
  (N'svetila_si', N'zunanja_svetila', N'GARANCIJA', N'RECOMMENDED', 91, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 70, N'znamke:2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'zunanja_svetila', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 91, N'znamke:2A1+2A10+2A13+2A6+2A7+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 58, N'znamke:2A1+2A6'),
  (N'svetila_si', N'zunanja_svetila', N'NACIN_MONTAZE', N'RECOMMENDED', 89, N'znamke:2A1+2A6+2A7+2A9+2A7'),
  (N'svetila_si', N'zunanja_svetila', N'NAPETOST', N'RECOMMENDED', 89, N'znamke:2A1+2A6+2A7+2A1+2A6+2A7+2A7'),
  (N'svetila_si', N'zunanja_svetila', N'NAZIVNA_MOC', N'RECOMMENDED', 77, N'znamke:2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'zunanja_svetila', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 96, N'znamke:2A1+2A6'),
  (N'svetila_si', N'zunanja_svetila', N'OBLIKA_SVETILKE', N'RECOMMENDED', 83, N'znamke:2A1+2A6+2A9+2A5+2A7+2A9+2A6+2A5'),
  (N'svetila_si', N'zunanja_svetila', N'PREVLADUJOC_MATERIAL', N'RECOMMENDED', 90, N'znamke:2A1+2A5+2A6+2A7+2A9+2A13'),
  (N'svetila_si', N'zunanja_svetila', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 90, N'znamke:2A1+2A10+2A13+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'SENZOR_GIBANJA', N'RECOMMENDED', 93, N'znamke:2A1+2A6+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'SIRINA', N'RECOMMENDED', 70, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'SLOG', N'RECOMMENDED', 77, N'znamke:2A1+2A10+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'SVETLOBNI_TOK', N'RECOMMENDED', 73, N'znamke:2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'zunanja_svetila', N'TEMPERATURA_BARVE', N'RECOMMENDED', 76, N'znamke:2A1+2A6+2A9+2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'zunanja_svetila', N'UPORABA', N'RECOMMENDED', 92, N'znamke:2A1+2A6+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'VISINA', N'RECOMMENDED', 84, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 79, N'znamke:2A1+2A6+2A9+2A13'),
  (N'svetila_si', N'zunanja_svetila', N'ZATEMNLJIVO', N'RECOMMENDED', 92, N'znamke:2A1+2A6+2A7+2A9'),
  (N'svetila_si', N'zunanja_svetila', N'ZIVLJENJSKA_DOBA', N'RECOMMENDED', 79, N'znamke:2A1+2A13+2A6'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'BATERIJA', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'DELOVNA_TEMPERATURA', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'DOLZINA', N'RECOMMENDED', 80, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'ELEKTRICNI_RAZRED', N'RECOMMENDED', 80, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'GARANCIJA', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'NACIN_POLNJENJA', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'NAZIVNA_MOC', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'SIRINA', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'UPORABA', N'RECOMMENDED', 60, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'VISINA', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'ZATEMNLJIVO', N'RECOMMENDED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'KOT_SVETLOBNEGA_SNOPA', N'REQUIRED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'NAPETOST', N'REQUIRED', 100, N'2A3,2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2A3,2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'SVETLOBNI_TOK', N'REQUIRED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'TEMPERATURA_BARVE', N'REQUIRED', 100, N'2A3,2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'VRSTA_SVETLOBNEGA_VIRA', N'REQUIRED', 100, N'2A3'),
  (N'svetila_si', N'zunanja_svetila___prenosna_svetila', N'ZIVLJENJSKA_DOBA', N'REQUIRED', 100, N'2A3'),
  (N'videlektro', N'instalacije___elektro_omare_in_razdelilniki', N'DELOVNA_TEMPERATURA', N'REQUIRED', 100, N'1H,1H2'),
  (N'videlektro', N'instalacije___elektro_omare_in_razdelilniki', N'DOLZINA', N'REQUIRED', 100, N'1H,1H2'),
  (N'videlektro', N'instalacije___elektro_omare_in_razdelilniki', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1H,1H2'),
  (N'videlektro', N'instalacije___elektro_omare_in_razdelilniki', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'1H,1H2'),
  (N'videlektro', N'instalacije___elektro_omare_in_razdelilniki', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1H,1H2'),
  (N'videlektro', N'instalacije___elektro_omare_in_razdelilniki', N'SIRINA', N'REQUIRED', 100, N'1H,1H2'),
  (N'videlektro', N'instalacije___elektro_omare_in_razdelilniki', N'VISINA', N'REQUIRED', 100, N'1H,1H2'),
  (N'videlektro', N'instalacije___instalacijski_kanali', N'DOLZINA', N'REQUIRED', 100, N'1F,1F'),
  (N'videlektro', N'instalacije___instalacijski_kanali', N'NACIN_MONTAZE', N'REQUIRED', 100, N'1F'),
  (N'videlektro', N'instalacije___instalacijski_kanali', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'1F'),
  (N'videlektro', N'instalacije___instalacijski_kanali', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1F'),
  (N'videlektro', N'instalacije___instalacijski_kanali', N'SIRINA', N'REQUIRED', 100, N'1F'),
  (N'videlektro', N'instalacije___instalacijski_kanali', N'VISINA', N'REQUIRED', 100, N'1F'),
  (N'videlektro', N'instalacije___kabli_in_vodniki', N'DOLZINA', N'RECOMMENDED', 79, N'1A6'),
  (N'videlektro', N'instalacije___kabli_in_vodniki', N'GARANCIJA', N'RECOMMENDED', 87, N'1A6'),
  (N'videlektro', N'instalacije___kabli_in_vodniki', N'NAZIVNA_JAKOST_TOKA', N'RECOMMENDED', 58, N'1A6'),
  (N'videlektro', N'instalacije___kabli_in_vodniki', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 84, N'1A6'),
  (N'videlektro', N'instalacije___kabli_in_vodniki', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 92, N'1A6'),
  (N'videlektro', N'instalacije___kabli_in_vodniki', N'SIRINA', N'RECOMMENDED', 84, N'1A6'),
  (N'videlektro', N'instalacije___kabli_in_vodniki', N'VISINA', N'RECOMMENDED', 82, N'1A6'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_koncniki_in_spojke', N'PRESEK_KABLA', N'RECOMMENDED', 86, N'1A3'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_koncniki_in_spojke', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1A3'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke', N'DELOVNA_TEMPERATURA', N'RECOMMENDED', 51, N'1A1'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke', N'PRESEK_KABLA', N'RECOMMENDED', 93, N'1A1'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke', N'PREVLADUJOC_MATERIAL', N'RECOMMENDED', 53, N'1A1'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke', N'DOLZINA', N'REQUIRED', 95, N'1A1'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1A1'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1A1,1A2'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spoji_in_zalivke', N'SIRINA', N'REQUIRED', 95, N'1A1'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spojni_material', N'DOLZINA', N'RECOMMENDED', 90, N'1A4'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spojni_material', N'NAZIVNA_JAKOST_TOKA', N'RECOMMENDED', 76, N'1A4'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spojni_material', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 94, N'1A4'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spojni_material', N'PREVLADUJOC_MATERIAL', N'RECOMMENDED', 91, N'1A4'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spojni_material', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 93, N'1A4'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spojni_material', N'SIRINA', N'RECOMMENDED', 90, N'1A4'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spojni_material', N'VISINA', N'RECOMMENDED', 90, N'1A4'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___kabelski_spojni_material', N'PRESEK_KABLA', N'REQUIRED', 95, N'1A4'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'DOLZINA', N'RECOMMENDED', 50, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'PRESEK_KABLA', N'RECOMMENDED', 67, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'SIRINA', N'RECOMMENDED', 50, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'VISINA', N'RECOMMENDED', 50, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'GARANCIJA', N'REQUIRED', 100, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'NAZIVNA_JAKOST_TOKA', N'REQUIRED', 100, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'NAZIVNA_MOC', N'REQUIRED', 100, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'NAZIVNA_NAPETOST', N'REQUIRED', 100, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1A5'),
  (N'videlektro', N'instalacije___kabli_in_vodniki___podaljski_in_razdelilci', N'VRSTA_KABLA', N'REQUIRED', 100, N'1A5'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'DELOVNA_TEMPERATURA', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'DOLZINA', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'FREKVENCA', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'GARANCIJA', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'NAPETOST', N'REQUIRED', 100, N'1B1,1B1,1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'NAZIVNA_JAKOST_TOKA', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'NAZIVNA_NAPETOST', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'PRESEK_KABLA', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'SIRINA', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___instalacijski_odklopniki', N'VISINA', N'REQUIRED', 100, N'1B1'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 58, N'1B2'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor', N'NACIN_MONTAZE', N'RECOMMENDED', 50, N'1B2'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor', N'NAZIVNA_JAKOST_TOKA', N'RECOMMENDED', 72, N'1B2'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 63, N'1B2'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor', N'PRESEK_KABLA', N'RECOMMENDED', 82, N'1B2'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 50, N'1B2'),
  (N'videlektro', N'instalacije___omare_in_stikalna_tehnika___zbiralke_in_pribor', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 97, N'1B2'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi', N'DELOVNA_TEMPERATURA', N'REQUIRED', 97, N'1C1'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi', N'DOLZINA', N'REQUIRED', 97, N'1C1,1C1'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 97, N'1C1'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi', N'PREVLADUJOCA_BARVA', N'REQUIRED', 97, N'1C1'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi', N'SIRINA', N'REQUIRED', 97, N'1C1,1C1'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___izolirni_trakovi', N'VISINA', N'REQUIRED', 97, N'1C1'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___objemke', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'1C2'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___objemke', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1C2'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___uvodnice', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1C3'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___uvodnice', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'1C3'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___uvodnice', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1C3'),
  (N'videlektro', N'instalacije___prikljucni_in_pritrdilni_material___uvodnice', N'VELIKOST', N'REQUIRED', 100, N'1C3'),
  (N'videlektro', N'instalacije___razvodne_doze', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 75, N'1G,1G2'),
  (N'videlektro', N'instalacije___razvodne_doze', N'DELOVNA_TEMPERATURA', N'REQUIRED', 100, N'1G2'),
  (N'videlektro', N'instalacije___razvodne_doze', N'DOLZINA', N'REQUIRED', 98, N'1G'),
  (N'videlektro', N'instalacije___razvodne_doze', N'GARANCIJA', N'REQUIRED', 100, N'1G2'),
  (N'videlektro', N'instalacije___razvodne_doze', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1G,1G2'),
  (N'videlektro', N'instalacije___razvodne_doze', N'NACIN_MONTAZE', N'REQUIRED', 100, N'1G,1G2'),
  (N'videlektro', N'instalacije___razvodne_doze', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'1G2'),
  (N'videlektro', N'instalacije___razvodne_doze', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1G,1G2'),
  (N'videlektro', N'instalacije___razvodne_doze', N'SIRINA', N'REQUIRED', 100, N'1G'),
  (N'videlektro', N'instalacije___razvodne_doze', N'VISINA', N'REQUIRED', 100, N'1G'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___klasicni_program', N'NACIN_MONTAZE', N'RECOMMENDED', 87, N'1D1'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___klasicni_program', N'NAZIVNA_JAKOST_TOKA', N'RECOMMENDED', 59, N'1D1'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___klasicni_program', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 61, N'1D1'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___klasicni_program', N'PREVLADUJOCA_BARVA', N'REQUIRED', 99, N'1D1'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___modularni_program', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 94, N'1D2'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___zvonci', N'NAZIVNA_JAKOST_TOKA', N'RECOMMENDED', 57, N'1D3'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___zvonci', N'GARANCIJA', N'REQUIRED', 100, N'1D3'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___zvonci', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1D3'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___zvonci', N'NACIN_MONTAZE', N'REQUIRED', 100, N'1D3'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___zvonci', N'NAZIVNA_NAPETOST', N'REQUIRED', 100, N'1D3'),
  (N'videlektro', N'instalacije___stikala_in_vticnice___zvonci', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1D3'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'DOLZINA', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'NAZIVNA_JAKOST_TOKA', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'NAZIVNA_NAPETOST', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'PRESEK_KABLA', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'SIRINA', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___strelovod_in_ozemljitev', N'VISINA', N'REQUIRED', 100, N'1J'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'DOLZINA', N'RECOMMENDED', 52, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'GARANCIJA', N'RECOMMENDED', 75, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'SIRINA', N'RECOMMENDED', 67, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'VISINA', N'RECOMMENDED', 54, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'NAZIVNA_JAKOST_TOKA', N'REQUIRED', 100, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'NAZIVNA_NAPETOST', N'REQUIRED', 100, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1I'),
  (N'videlektro', N'instalacije___vtikaci_in_vticnice', N'VRSTA_KABLA', N'REQUIRED', 95, N'1I'),
  (N'videlektro', N'orodje___elektricno_orodje', N'NAZIVNA_MOC', N'RECOMMENDED', 70, N'1E3'),
  (N'videlektro', N'orodje___elektricno_orodje', N'GARANCIJA', N'REQUIRED', 100, N'1E3'),
  (N'videlektro', N'orodje___elektricno_orodje', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'1E3'),
  (N'videlektro', N'orodje___prenosni_merilni_instrumenti', N'BATERIJA', N'RECOMMENDED', 66, N'1E4'),
  (N'videlektro', N'orodje___prenosni_merilni_instrumenti', N'DOLZINA', N'RECOMMENDED', 75, N'1E4'),
  (N'videlektro', N'orodje___prenosni_merilni_instrumenti', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 91, N'1E4'),
  (N'videlektro', N'orodje___prenosni_merilni_instrumenti', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 86, N'1E4'),
  (N'videlektro', N'orodje___prenosni_merilni_instrumenti', N'SIRINA', N'RECOMMENDED', 82, N'1E4'),
  (N'videlektro', N'orodje___prenosni_merilni_instrumenti', N'VISINA', N'RECOMMENDED', 84, N'1E4'),
  (N'videlektro', N'orodje___prenosni_merilni_instrumenti', N'GARANCIJA', N'REQUIRED', 100, N'1E4'),
  (N'videlektro', N'orodje___rocno_orodje___ostalo_orodje', N'PREVLADUJOC_MATERIAL', N'RECOMMENDED', 93, N'1E2'),
  (N'videlektro', N'orodje___rocno_orodje___ostalo_orodje', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 87, N'1E2'),
  (N'videlektro', N'orodje___rocno_orodje___ostalo_orodje', N'UPORABA', N'RECOMMENDED', 87, N'1E2'),
  (N'videlektro', N'orodje___rocno_orodje___ostalo_orodje', N'GARANCIJA', N'REQUIRED', 100, N'1E2'),
  (N'videlektro', N'orodje___rocno_orodje___predvleke', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 54, N'1E1'),
  (N'videlektro', N'orodje___rocno_orodje___predvleke', N'DOLZINA', N'REQUIRED', 99, N'1E1'),
  (N'videlektro', N'orodje___rocno_orodje___predvleke', N'PREMER', N'REQUIRED', 99, N'1E1'),
  (N'videlektro', N'orodje___rocno_orodje___predvleke', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 99, N'1E1,1E5'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'DOLZINA', N'RECOMMENDED', 91, N'2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'NAPETOST', N'RECOMMENDED', 67, N'2D,2D,2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'NAZIVNA_MOC', N'RECOMMENDED', 65, N'2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 53, N'2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'RAZDALJA_DETEKCIJE', N'RECOMMENDED', 66, N'2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'GARANCIJA', N'REQUIRED', 99, N'2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 99, N'2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'SIRINA', N'REQUIRED', 98, N'2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___kontrolerji_in_zatemnilniki', N'VISINA', N'REQUIRED', 98, N'2D'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki', N'DOLZINA', N'REQUIRED', 100, N'2B1,2B2,2B3,2B4,2B1,2B2'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki', N'GARANCIJA', N'REQUIRED', 97, N'2B3'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki', N'NACIN_MONTAZE', N'REQUIRED', 100, N'2B1,2B3'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2B1,2B2,2B3,2B4'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2B1,2B2,2B3,2B4,2B1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki', N'SIRINA', N'REQUIRED', 100, N'2B1,2B2,2B3,2B4'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_profili_in_dodatki', N'VISINA', N'REQUIRED', 100, N'2B1,2B2,2B3,2B4'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 89, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'DOLZINA', N'REQUIRED', 98, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'GARANCIJA', N'REQUIRED', 99, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'REQUIRED', 96, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 99, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'NAZIVNA_MOC', N'REQUIRED', 99, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'NAZIVNA_NAPETOST', N'REQUIRED', 99, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'SIRINA', N'REQUIRED', 99, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'SVETLOBNI_TOK', N'REQUIRED', 97, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'TEMPERATURA_BARVE', N'REQUIRED', 98, N'2C1,2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'VISINA', N'REQUIRED', 99, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___led_trakovi', N'ZIVLJENJSKA_DOBA', N'REQUIRED', 95, N'2C1'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'DOLZINA', N'REQUIRED', 99, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'GARANCIJA', N'REQUIRED', 100, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 100, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'NACIN_MONTAZE', N'REQUIRED', 100, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'NAPETOST', N'REQUIRED', 100, N'2E,2E,2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'NAZIVNA_JAKOST_TOKA', N'REQUIRED', 99, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'NAZIVNA_MOC', N'REQUIRED', 100, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'NAZIVNA_NAPETOST', N'REQUIRED', 100, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'SIRINA', N'REQUIRED', 100, N'2E'),
  (N'videlektro', N'razsvetljava___led_trakovi_in_profili___napajalniki', N'VISINA', N'REQUIRED', 99, N'2E'),
  (N'videlektro', N'razsvetljava___luci', N'DOLZINA', N'RECOMMENDED', 86, N'znamke:2A1+2A13'),
  (N'videlektro', N'razsvetljava___luci', N'FREKVENCA', N'RECOMMENDED', 90, N'znamke:2A7+2A6'),
  (N'videlektro', N'razsvetljava___luci', N'GARANCIJA', N'RECOMMENDED', 91, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'RECOMMENDED', 70, N'znamke:2A1+2A6+2A9+2A13'),
  (N'videlektro', N'razsvetljava___luci', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 91, N'znamke:2A1+2A10+2A13+2A6+2A7+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'KOT_SVETLOBNEGA_SNOPA', N'RECOMMENDED', 58, N'znamke:2A1+2A6'),
  (N'videlektro', N'razsvetljava___luci', N'NACIN_MONTAZE', N'RECOMMENDED', 89, N'znamke:2A1+2A6+2A7+2A9+2A7'),
  (N'videlektro', N'razsvetljava___luci', N'NAPETOST', N'RECOMMENDED', 89, N'znamke:2A1+2A6+2A7+2A1+2A6+2A7+2A7'),
  (N'videlektro', N'razsvetljava___luci', N'NAZIVNA_MOC', N'RECOMMENDED', 77, N'znamke:2A1+2A6+2A9+2A13'),
  (N'videlektro', N'razsvetljava___luci', N'OBLIKA_SVETILKE', N'RECOMMENDED', 83, N'znamke:2A1+2A6+2A9+2A5+2A7+2A9+2A6+2A5'),
  (N'videlektro', N'razsvetljava___luci', N'PREVLADUJOC_MATERIAL', N'RECOMMENDED', 90, N'znamke:2A1+2A5+2A6+2A7+2A9+2A13'),
  (N'videlektro', N'razsvetljava___luci', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 90, N'znamke:2A1+2A10+2A13+2A5+2A6+2A7+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'SENZOR_GIBANJA', N'RECOMMENDED', 93, N'znamke:2A1+2A6+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'SIRINA', N'RECOMMENDED', 70, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'SLOG', N'RECOMMENDED', 77, N'znamke:2A1+2A10+2A5+2A6+2A7+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'SVETLOBNI_TOK', N'RECOMMENDED', 73, N'znamke:2A1+2A6+2A9+2A13'),
  (N'videlektro', N'razsvetljava___luci', N'TEMPERATURA_BARVE', N'RECOMMENDED', 76, N'znamke:2A1+2A6+2A9+2A1+2A6+2A9+2A13'),
  (N'videlektro', N'razsvetljava___luci', N'UPORABA', N'RECOMMENDED', 92, N'znamke:2A1+2A6+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'VISINA', N'RECOMMENDED', 84, N'znamke:2A1+2A5+2A6+2A7+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 79, N'znamke:2A1+2A6+2A9+2A13'),
  (N'videlektro', N'razsvetljava___luci', N'ZATEMNLJIVO', N'RECOMMENDED', 92, N'znamke:2A1+2A6+2A7+2A9'),
  (N'videlektro', N'razsvetljava___luci', N'ZIVLJENJSKA_DOBA', N'RECOMMENDED', 79, N'znamke:2A1+2A13+2A6'),
  (N'videlektro', N'razsvetljava___luci', N'NAZIVNA_NAPETOST', N'REQUIRED', 96, N'znamke:2A1+2A6'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'DOLZINA', N'RECOMMENDED', 71, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 53, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'NACIN_MONTAZE', N'RECOMMENDED', 90, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'OBLIKA_SVETILKE', N'RECOMMENDED', 76, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'PREVLADUJOC_MATERIAL', N'RECOMMENDED', 61, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 85, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'SIRINA', N'RECOMMENDED', 86, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'VISINA', N'RECOMMENDED', 86, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___dodatki', N'UPORABA', N'REQUIRED', 100, N'2A15'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'DELOVNI_CAS', N'RECOMMENDED', 88, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'DOLZINA', N'RECOMMENDED', 62, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'FREKVENCA', N'RECOMMENDED', 77, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'GARANCIJA', N'RECOMMENDED', 88, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'IP_STOPNJA_ZASCITE', N'RECOMMENDED', 73, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'NACIN_MONTAZE', N'RECOMMENDED', 88, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'NAPETOST', N'RECOMMENDED', 77, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'NAZIVNA_MOC', N'RECOMMENDED', 65, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'NAZIVNA_NAPETOST', N'RECOMMENDED', 77, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'OBLIKA_SVETILKE', N'RECOMMENDED', 88, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'PREVLADUJOCA_BARVA', N'RECOMMENDED', 92, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'SENZOR_GIBANJA', N'RECOMMENDED', 88, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'SIRINA', N'RECOMMENDED', 88, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'SVETLOBNI_TOK', N'RECOMMENDED', 62, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'TEMPERATURA_BARVE', N'RECOMMENDED', 69, N'2A2,2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'VISINA', N'RECOMMENDED', 88, N'2A2'),
  (N'videlektro', N'razsvetljava___luci___zasilna_razsvetljava', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 85, N'2A2'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___dodatki_k_senzorjem', N'NACIN_MONTAZE', N'RECOMMENDED', 83, N'2F2,2F2'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___dodatki_k_senzorjem', N'OBLIKA_SVETILKE', N'RECOMMENDED', 72, N'2F2'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___dodatki_k_senzorjem', N'SIRINA', N'RECOMMENDED', 53, N'2F2'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___dodatki_k_senzorjem', N'VISINA', N'RECOMMENDED', 53, N'2F2'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___dodatki_k_senzorjem', N'PREVLADUJOCA_BARVA', N'REQUIRED', 97, N'2F2'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'DELOVNI_CAS', N'RECOMMENDED', 88, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'DOLZINA', N'RECOMMENDED', 57, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'KOT_DETEKCIJE', N'RECOMMENDED', 92, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'MONTAZNA_VISINA', N'RECOMMENDED', 89, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'RAZDALJA_DETEKCIJE', N'RECOMMENDED', 92, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'SENZOR_GIBANJA', N'RECOMMENDED', 92, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'DELOVNA_TEMPERATURA', N'REQUIRED', 95, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'GARANCIJA', N'REQUIRED', 100, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 99, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'NACIN_MONTAZE', N'REQUIRED', 98, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'NAPETOST', N'REQUIRED', 97, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'NAZIVNA_NAPETOST', N'REQUIRED', 97, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'OBLIKA_SVETILKE', N'REQUIRED', 99, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'SIRINA', N'REQUIRED', 98, N'2F1'),
  (N'videlektro', N'razsvetljava___senzorji_gibanja___senzorji', N'VISINA', N'REQUIRED', 99, N'2F1'),
  (N'videlektro', N'razsvetljava___sijalke', N'VRSTA_SVETLOBNEGA_VIRA', N'RECOMMENDED', 90, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'EKVIVALENT', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'ENERGIJSKI_RAZRED', N'REQUIRED', 99, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'GARANCIJA', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'GRLO', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'INDEKS_BARVNEGA_VIDEZA_CRI', N'REQUIRED', 99, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'IP_STOPNJA_ZASCITE', N'REQUIRED', 99, N'2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'KOT_SVETLOBNEGA_SNOPA', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'NAPETOST', N'REQUIRED', 100, N'2G1,2G2,2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'NAZIVNA_MOC', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'NAZIVNA_NAPETOST', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'OBLIKA_SVETILKE', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'SENZOR_GIBANJA', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'SIRINA', N'REQUIRED', 99, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'SVETLOBNI_TOK', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'TEMPERATURA_BARVE', N'REQUIRED', 100, N'2G1,2G2,2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'VISINA', N'REQUIRED', 99, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'ZATEMNLJIVO', N'REQUIRED', 100, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___sijalke', N'ZIVLJENJSKA_DOBA', N'REQUIRED', 99, N'2G1,2G2'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'DOLZINA', N'RECOMMENDED', 87, N'2H1'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'NACIN_MONTAZE', N'RECOMMENDED', 92, N'2H1'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'SIRINA', N'RECOMMENDED', 87, N'2H1'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'VISINA', N'RECOMMENDED', 77, N'2H1'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'GARANCIJA', N'REQUIRED', 100, N'2H1'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'PREVLADUJOC_MATERIAL', N'REQUIRED', 100, N'2H1'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'PREVLADUJOCA_BARVA', N'REQUIRED', 100, N'2H1,2H1'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'SLOG', N'REQUIRED', 100, N'2H1'),
  (N'videlektro', N'razsvetljava___tracni_sistemi', N'UPORABA', N'REQUIRED', 100, N'2H1');

/* Ze rocno urejena AKTIVNA vrstica obvelja: master je izhodisce, ne zadnja beseda. Neaktivna
   (odstranjena ali testna, npr. 'test 147') se z mastrom znova vklopi. */
DELETE seed FROM @Seed AS seed
WHERE EXISTS (SELECT 1 FROM canon.CategoryAttributeSet AS existing
  WHERE existing.CategoryTreeCode = seed.CategoryTreeCode AND existing.CategoryCode = seed.CategoryCode
    AND existing.AttributeCode = seed.AttributeCode AND existing.IsActive = 1
    AND existing.UpdatedBy <> N'mastri 2026-09-08');

DECLARE @Tree nvarchar(100), @Category nvarchar(200), @Json nvarchar(max), @Saved int, @Total int = 0;
DECLARE category_cursor CURSOR LOCAL FAST_FORWARD FOR
  SELECT CategoryTreeCode, CategoryCode FROM @Seed GROUP BY CategoryTreeCode, CategoryCode ORDER BY MIN(Seq);
OPEN category_cursor;
FETCH NEXT FROM category_cursor INTO @Tree, @Category;
WHILE @@FETCH_STATUS = 0
BEGIN
  SET @Json = (SELECT code = AttributeCode, level = Level FROM @Seed
               WHERE CategoryTreeCode = @Tree AND CategoryCode = @Category ORDER BY Seq FOR JSON PATH);
  EXEC canon.SaveCategoryAttributeSetBulk @Tree, @Category, @Json, N'mastri 2026-09-08', @Saved OUTPUT;
  SET @Total += @Saved;
  FETCH NEXT FROM category_cursor INTO @Tree, @Category;
END;
CLOSE category_cursor; DEALLOCATE category_cursor;
PRINT CONCAT(N'173: nabori iz mastrov — zapisanih vrstic: ', @Total);
