<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PIM.XmlMapping/PIM.XmlMapping.csproj" />
    <!-- LocalSettings: skupno iskanje ene same appsettings.Local.json rešitve. -->
    <ProjectReference Include="../../src/PIM.Operations/PIM.Operations.csproj" />
  </ItemGroup>
</Project>
